# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# GitHub Actions CI build configuration

name: Ibex OSS Formal CI

on:
  push:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'dv/formal/**'
      - 'rtl/**'
      - 'vendor/**'
      - '.github/**'
  merge_group:
    types:
      - checks_requested
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'dv/formal/**'
      - 'rtl/**'
      - 'vendor/**'
      - '.github/**'

jobs:
  fv:
    name: Run the Open-Source FV flow
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        run: |
          echo "NIX_CONFIG=accept-flake-config = true" >> $GITHUB_ENV

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            substituters = https://nix-cache.lowrisc.org/public/ https://cache.nixos.org/
            trusted-public-keys = nix-cache.lowrisc.org-public-1:O6JLD0yXzaJDPiQW1meVu32JIDViuaPtGDfjlOopU7o= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Run OSS Env
        run: |
          source <(nix print-dev-env .#oss-dev)

          cd dv/formal
          make build/aig-manip
          make build/all.aig SHELL=bash
          python3 conductor.py prove --check-complete
          # add --max-mem <gb> to restrict to some upper bound on memory usage. Hard minimum is 20 but 128 is a more realistic minimum

